version: "3.9"
services:
  bencher_api:
    image: ghcr.io/bencherdev/bencher-api-local:latest
    container_name: bencher_api_local
    ports:
      - 61016:61016
    volumes:
      - "./data:/data"
      # environment:
      # Set configuration string or file path
      # - BENCHER_CONFIG=
      # - BENCHER_CONFIG_PATH=

  bencher_ui:
    image: ghcr.io/bencherdev/bencher-ui:latest
    container_name: bencher_ui
    ports:
      - 3000:80
    depends_on:
      - bencher_api
