[package]
name = "bencher_cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["plus"]
plus = ["bencher_client/plus", "bencher_json/plus"]
seed = []

[dependencies]
# Workspace
bencher_adapter.workspace = true
bencher_client.workspace = true
bencher_comment.workspace = true
bencher_json = { workspace = true, features = ["lite", "table"] }
chrono = { workspace = true, features = ["clock"] }
clap.workspace = true
literally.workspace = true
octocrab.workspace = true
once_cell.workspace = true
progenitor-client.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
tabled.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "process", "rt", "signal"] }
url.workspace = true
# Crate
bollard = "0.15"
futures-util = "0.3"

# TODO upstream the `winerror` feature
# https://github.com/fussybeaver/bollard/blob/af08c3cb328654154ff63beaf23eedb201230215/Cargo.toml#L88C1-L89C17
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winerror"] }

[dev-dependencies]
# Workspace
pretty_assertions.workspace = true
# Crate
assert_cmd = "2.0"

[lints]
workspace = true

[[bin]]
name = "bencher"
path = "src/main.rs"
