[package]
name = "bencher_cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["plus"]
docs = ["dep:clap_mangen"]
plus = ["bencher_client/plus", "bencher_json/plus"]
seed = []

[dependencies]
# Workspace
async-trait.workspace = true
bencher_adapter.workspace = true
bencher_client.workspace = true
bencher_json = { workspace = true, features = ["lite", "table"] }
chrono = { workspace = true, features = ["clock"] }
clap.workspace = true
literally.workspace = true
once_cell.workspace = true
progenitor-client.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
tabled.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "process", "rt"] }
url.workspace = true
# Crate
clap_mangen = { version = "0.2", optional = true }
octocrab = "0.32"

[dev-dependencies]
# Workspace
pretty_assertions.workspace = true
# Crate
assert_cmd = "2.0"

[[bin]]
name = "bencher"
path = "src/main.rs"
