version: "3.9"
services:
  bencher_api_builder:
    build:
      context: ..
      dockerfile: ./services/api/builder.Dockerfile
      args:
        - MOLD_VERSION=2.4.0
    image: bencher-api-builder
    container_name: bencher_api_builder

  bencher-ui-builder:
    build:
      context: ..
      dockerfile: ./services/console/builder.Dockerfile
      args:
        - MOLD_VERSION=2.4.0
    image: bencher-ui-builder
    container_name: bencher_ui_builder
