version: "3.9"
services:
  bencher_api_compose:
    build:
      context: ..
      dockerfile: ./services/api/builder.Dockerfile
      args:
        LITESTREAM_ARCH: amd64
        ARCH: x86_64
        ZIG_VERSION: 0.12.0-dev.2341+92211135f
    image: bencher-api
    container_name: bencher_api
    ports:
      - 61016:61016
    volumes:
      - "../services/api/data:/usr/bin/bencher/data"
    environment:
      # Set configuration string or filepath
      # BENCHER_CONFIG: '{}'
      BENCHER_CONFIG_PATH: /usr/bin/bencher/data/bencher.json

  # bencher-ui-builder:
  #   build:
  #     context: ..
  #     dockerfile: ./services/console/builder.Dockerfile
  #     args:
  #       - MOLD_VERSION=2.4.0
  #   image: bencher-ui-builder
  #   container_name: bencher_ui_builder
