app = "bencher-api-test"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "6s"

[build]
image = "registry.fly.io/bencher-api-test"

[env]
LITESTREAM_DB_PATH = "/data/bencher.db"

[[services]]
protocol = "tcp"
internal_port = 61016

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
