[package]
name = "bencher_license"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# Workspace
bencher_json = { workspace = true, features = ["full", "plus"] }
chrono.workspace = true
jsonwebtoken = { workspace = true, features = ["use_pem"] }
once_cell.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true

[lints]
workspace = true
